//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Employee
    {
		
        public int EmployeeId { get; set; }
		
		public string Name { get; set; }
		[Required]
		public string Gender { get; set; }
		[Required]
		public string City { get; set; }
		[Display(Name = "Department")]
		[Required]
		public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }

	internal class requiureAttribute : Attribute
	{
	}
}
